config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :records do
    get 'upload', on: :new
  end

  namespace :admin do
    resources :users
  end

  root 'summary#index'










end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  delegate :name, :to => :user, :prefix => :user, :allow_nil => true
  enum status: [:pending, :reviewed, :approved, :rejected, :received]
  enum category: {electrical: 0, battery: 1, chemical: 2, mechanical: 3, conference: 4, outreach: 5, flow_battery: 6, misc: 7}
  
  validates :item, presence: true
  validates :description, presence: true
  validates :part_number, presence: true
  validates_format_of :price, :with => /\A\d+\.*\d{0,2}\z/
  validates :quantity, numericality: { only_integer: true }
  validates :category, presence: true
  validates :supplier, presence: true
  validates :link, presence: true
  validates :status, presence: true

  attr_reader :total_price
  def total_price
    return quantity*price
  end

  def self.to_csv
    attributes = %w{id created_at item description user_name quantity price category supplier part_number link total_price status updated_at }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: [:update, :edit]

  def redirect_to_back(default = records_path)
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end

  def require_permission
    if !current_user.try(:admin?) and current_user.id != @record.user_id
      redirect_to_back
      flash[:alert] = "You do not have permission to edit this record."
    end
  end
  
  # GET /records
  # GET /records.json
  def index
    approved_stages = [2,4]
    @total_expenses = Record.where.not(status: 3).sum("quantity*price")
    @approved_expenses = Record.where(:status => approved_stages).sum("quantity*price") 
    @total_revenue = 25000
    @budget_balance = @total_revenue - @total_expenses
    
    if params[:status] == "pending"
      @records = Record.pending
    elsif params[:status] == "reviewed"
      @records = Record.reviewed
    elsif params[:status] == "approved"
      @records = Record.where(:status => approved_stages)      
    elsif params[:status] == "rejected"
      @records = Record.rejected
    else
      @records = Record.where.not(status: 3).order! 'created_at DESC'
    end
    respond_to do |format|
      format.html
      format.csv { send_data Record.all.to_csv, filename: "ubc-chemecar-#{Date.today}.csv" }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    @record.status = 'pending'

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        flash[:success] = "Record Updated"
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { respond_with_bip(@record) }
        # format.json { render :show, status: :ok, location: @record }
      else
        flash[:error] = "Record Update Error"
        format.html { render :edit }
        format.json { respond_with_bip(@record) }
        # format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:item, :description, :price, :quantity, :part_number, :supplier, :link, :status, :category)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= bootstrap_form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Flag if buying in-store!", rows: 8 %>
  </div>
  <div class="field">
    <%= f.select :category, Record.categories.keys %>
  </div>  
  <div class="field">
    <%= f.number_field :price, :placeholder => "Unit Price ($CAD)", :class => 'text_field', :step => 0.01 %>
  </div>
  <div class="field">
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.text_field :part_number%>
  </div>  
  <div class="field">
    <%= f.text_field :link %>
  </div>
  <% if current_user.try(:admin?) %>
  <div class="field">
    <%= f.select :status, Record.statuses.keys %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<div class="col-xs-12 col-md-6">
  <%= render 'form' %>
  <h2>
    <%= link_to 'Show', @record %> |
    <%= link_to 'Back', records_path %>
  </h2>
</div>

app/views/records/index.html.erb
<%= button_to "Export As CSV", {action: "index", format:"csv"}, method:"get", class:"btn btn-primary pull-right" %>
<h1>
 Records | 
<small><%= link_to 'Request Item', new_record_path %></small> | 
<small><%= link_to 'Upload Excel', new_record_path %></small>
</h1>
<hr>
<div class="row">

  <div class="col-lg-3">
    <div class="panel panel-success">
      <div class="panel-heading">Approved Expenses ($CAD)</div>
      <div class="panel-footer"><%= number_to_currency(@approved_expenses) %></div>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="panel panel-danger">
      <div class="panel-heading">Total Expenses ($CAD)</div>
      <div class="panel-footer"><%= number_to_currency(@total_expenses) %></div>
    </div>
  </div>

  <% if current_user.try(:admin?) %>
  <div class="col-lg-3">
    <div class="panel panel-success">
      <div class="panel-heading">Revenue ($CAD)</div>
      <div class="panel-footer"><%= number_to_currency(@total_revenue) %></div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-info">
      <div class="panel-heading">Balance ($CAD)</div>
      <div class="panel-footer"><%= number_to_currency(@budget_balance) %></div>
    </div>
  </div>    
  <% end %>

</div>
<hr>

<p>
Show: 
<%= link_to 'All Items', action:"index" %> | 
<span class="bg-warning"><%= link_to 'Pending', action:"index", status: 'pending' %></span> |
<span class="bg-info"><%= link_to 'Reviewed', action:"index", status: 'reviewed' %></span> |
<span class="bg-success"><%= link_to 'Approved', action:"index", status: 'approved' %></span> |
<span class="bg-danger"><%= link_to 'Rejected', action:"index", status: 'rejected' %></span>
</p>

<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Item ID</th>
      <th>Item Name</th>
      <th>Date</th>
      <th>Requested By</th>
      <th>Description</th>
      <th>Category</th>
      <th>Supplier</th>
      <th>Part #</th>
      <th>Total Price ($CAD)</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.id %></td>
        <td><%= best_in_place record, :item, inner_class: 'form-control' %></td>
        <td><%= record.created_at.strftime("%d %b %Y") %></td>
        <td><%= record.user_name %></td>
        <td><%= best_in_place record, :description, :confirm => true, :type => :textarea, inner_class: 'form-control' %></td>
        <td><%= record.category.capitalize %></td>
        <td><%= record.supplier %></td>
        <td><%= record.part_number %></td>
        <td><%= number_to_currency(record.total_price) %></td>
        <td><%= record.status.capitalize %></td>
        <td>
          <% if current_user.try(:admin?) %>
            <p><b><%= link_to 'Review', edit_record_path(record) %></b></p>
          <% end %>
          <p><b><%= link_to 'Details', record %></b></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/records/new.html.erb
<h1>I want to buy:</h1>
<hr>

<div class="col-xs-12 col-md-6">
  <%= render 'form' %>
  <h2>
    <%= link_to 'Back', records_path %>
  </h2>  
</div>

app/views/records/show.html.erb
<p>
  <strong>Item:</strong>
  <%= @record.item %>
</p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Created On:</strong>
  <%= @record.created_at.strftime("%d %b %Y") %>
</p>

<p>
  <strong>Requested By:</strong>
  <%= @record.user_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @record.category %>
</p>

<p>
  <strong>Unit Price ($CAD):</strong>
  <%= number_to_currency(@record.price) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @record.quantity %>
</p>

<p>
  <strong>Total Price ($CAD):</strong>
  <%= number_to_currency(@record.total_price) %>
</p>


<p>
  <strong>Supplier:</strong>
  <%= @record.supplier %>
</p>

<p>
  <strong>Part Number:</strong>
  <%= @record.part_number %>
</p>


<p>
  <strong>Link:</strong>
  <%= @record.link %>
</p>

<hr>

<p>
  <strong>Status:</strong>
  <%= @record.status %>
</p>

<p>
  <strong>Updated On:</strong>
  <%= @record.updated_at.strftime("%d %b %Y at %H:%M:%S") %>
</p>

<% if current_user.id == @record.user_id or current_user.admin? %>
  <%= link_to 'Edit', edit_record_path(@record) %> |
<% end %>

<%= link_to 'Back', records_path %>