config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :records do
    get 'upload', on: :new
  end

  namespace :admin do
    resources :users
  end

  root 'summary#index'










end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  enum team: [:administrator, :battery, :electrical, :chemical, :mechanical, :misc]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end         

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message
    end 
  end  
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_permission, only: [:update, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def redirect_to_back(default = records_path)
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end

  def require_permission
    if !current_user.try(:admin?)
      redirect_to_back
      flash[:alert] = "User authentication failed, you need to check your privilege."
    end
  end

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.where(approved: true)
    end

    respond_to do |format|
      format.html
      format.json { render json: @users, :only => [:id, :biography] }
    end    
  
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @user, :only => [:id, :biography] }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :approved, :team, :biography)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def redirect_to_back(default = records_path)
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end

  def require_permission
    if !current_user.admin?
      redirect_to_back
      flash[:alert] = "You do not have permission to view users."
    end
  end

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.all
    end    
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :approved)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= bootstrap_form_for @user, :url => admin_user_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.select :team, User.teams.keys %>
  </div>  
  <div class="field">
    <%= f.text_area :biography, placeholder: "Linked to website profile", rows: 8 %>
  </div>  
  <% if current_user.try(:admin?) %>
  <div class="field">
    <%= f.check_box :approved %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>Team Roster
<small>2016/2017 UBC Chem-E-Car Members</small></h1>
<br>

<% if current_user.try(:admin?) %> 
<%= link_to 'All Users', action:"index" %> | 
<%= link_to 'Users Awaiting Approval', action:"index", approved:"false" %>
<% end %>

<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Team</th>
      <th>Bio</th>
      <th>Contact</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.team.capitalize %></td>
        <td><%= user.biography %></td>
        <td><%= user.email %></td>
        <td>
        <% if user.approved == "true" %>
          <p class="bg-success">
        <% elsif user.approved == "false" %>
          <p class="bg-danger">
        <% end %>
        <%= user.approved %></p>
        </td>
        <td>
        <%= link_to "Details", admin_user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Team:</strong>
  <%= @user.team %>
</p>

<p>
  <strong>Approved?</strong>
  <%= @user.approved %>
</p>

<p>
  <strong>Admin?</strong>
  <%= @user.admin %>
</p>

<% if current_user.try(:id) == @user.id or current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_admin_user_path(@user) %> |
<% end %>

<%= link_to 'Back', admin_users_path %>